name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Python Linter
      uses: sunnysid3up/python-linter@v0.1-beta.7
